name: SideBar
version: 1.0.0
api-version: 1.13
description: "A plugin to make personal scorecards."
author: oscardoras
main: me.oscardoras.sidebar.SideBarPlugin
permissions:
  sidebar:
    default: op
    children:
      sidebar.command: true
  sidebar.command:
    default: op
    children:
      sidebar.command.sidebar: true
  sidebar.command.sidebar:
    default: op